# Generated by Django 4.2.3 on 2023-07-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_employee_authorization_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=50, verbose_name="이름"),
        ),
    ]
