# Generated by Django 4.2.3 on 2023-07-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_reason_for_refusal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resignation",
            name="resigned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="퇴사일"),
        ),
    ]
